config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    resources :sessions, only: [:new, :create, :destroy]
    root  'static_pages#home'
    resources :users 
    match '/signin',  to: 'sessions#new',         via: 'get'
    match '/signout', to: 'sessions#destroy',     via: 'delete'
    match '/signup', to:'users#new', via:'get'
    match '/help', to:'static_pages#help', via:'get'
    match '/about', to:'static_pages#about', via:'get'
    match '/contact', to:'static_pages#contact', via:'get'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
 has_attached_file :avatar
validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
    
 
  
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    
    def create
       user = User.find_by(email: params[:session][:email].downcase)
       if user && user.authenticate(params[:session][:password])
           sign_in user
           redirect_back_or user
       else
         flash[:error] = 'Invalid email/password combination' # Not quite right!
         render 'new'
       end
    end
    
    def destroy
      sign_out
      redirect_to root_url
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
    
  def index
      @users=User.all
      
  end
    
  def edit
      @user=User.find(params[:id])
  end
    
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
       flash[:success] = "Profile updated"
       redirect_to @user
    else
      render 'edit'
    end
  end
    
  def show
      @user=User.find(params[:id])
  end
    
  def new
      @user=User.new
  end
  
  def create
      @user=User.new(user_params)
      if @user.save
          flash[:success] = "Welcome to the Communicatron!"
          redirect_to @user
      else
        render 'new'
      end
  end
    
  private
    def user_params
        params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :avatar)
    end
    
    # Before filters
    def signed_in_user
      store_location
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end
    
  def signed_in?
    !current_user.nil?
  end
    
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
    
  def current_user?(user)
    user == current_user
  end
    
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end
    
  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
    
  #Для того чтобы перенаправить пользователей к запрашиваемой ими странице, нам нужно где-то сохранить запрашиваемую страницу, а затем переадресовать к ней. Мы добьемся этого с помощью пары методов, store_location и redirect_back_or, определенных в хелпере Sessions 
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
   
end

app/views/layouts/_footer.html.erb
<footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                 <%= debug(params) if Rails.env.development? %>
              </div>
              <div class="col l4 offset-l2 s12 ">
                <ul>
                  <li><%= link_to "About", about_path, class:"grey-text text-lighten-3" %></li>
                  <li><%= link_to "Contact", contact_path, class:"grey-text text-lighten-3" %></li>
                  <li><%= link_to "News", "http://news.railstutorial.org/", class:"grey-text text-lighten-3" %></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
                <a href="http://railstutorial.org/" class="grey-text text-lighten-3">Rails Tutorial By Michael Hartl </a>    
            </div>
          </div>
        </footer>

app/views/layouts/_header.html.erb
<nav>
  <div class="nav-wrapper">
    <a href="#!" class="brand-logo">Logo</a>
    <ul class="right hide-on-med-and-down">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
      <!-- Dropdown Trigger -->
        <% if signed_in? %>
            
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li><%= link_to "Users" , users_path %></li>
            
              <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
            
        <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ruby on Rails Tutorial Communicatron | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag  "https://fonts.googleapis.com/icon?family=Material+Icons" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <div id="page-wrapper">
      <%= render 'layouts/header' %>
      <div class="container">
          <% flash.each do |key, value| %>
            <div class="alert <%= key %>"><%= value %></div>
          <% end %>
          <%= yield %>      
      </div>
  </div>
  <%= render 'layouts/footer' %>
 
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About Us</h1>
<p>
  About
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<h1 class="welcome" id="welcome-welcome"> Welcome to the</h1>
<h1 class="welcome" id="welcome-communicatron">Communicatron</h1>
<div id="button">
    <%= link_to "Sign up now!!!", signup_path, class:"waves-effect waves-light btn-large "  %>
       
   
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
        <%= image_tag user.avatar.url, size: "90x90", class:"circle" %>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
      
      <%= f.label :avatar %>
      <%= f.file_field :avatar %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<p></p>
<p><%= image_tag @user.avatar.url, size: "90x90", class:"circle" %></p>
<p><%= @user.name %></p>